include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    comment_references: false
    avoid_redundant_argument_values: false
    require_trailing_commas: false
